export const words = {
  Freeshipping: "Free shipping",
  any: "any 2+ items ot $50+!",
  numbers: "1.888.676.2660",
  time: "6AM 8PMST",
  footerInfo: "Information",
  FAQ: "FAQ",
  About: "About Us",
  More: "More Search",
  Blog: "Blog",
  Testmonials: "Testmonials",
  Events: "Events",
  Helpful: "Helpful Links",
  Services: "Services",
  Supports: "Supports",
  Terms: "Terms & Condtion",
  Policy: "Policy",
  Social: "Social Media",
  Sign: "Sign Up",
  p: "It is a long established fact that a reader will be distracted by the readable content .",
  filter: ["ALL", "Sm", "Xxl", "Xl", "Md", "Lg"],
  order: ["Latest", "Lowest", "Highest"],
};
//
